config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root 'resources#index'
  resources :resources

  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'users', only: [:show, :create] do
    resource :password,
             controller: 'clearance/passwords',
             only: [:create, :edit, :update]
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'clearance/users#new', as: 'sign_up'
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resource.rb
# frozen_string_literal: true
class Resource < ApplicationRecord
  validates_presence_of :link
  validates_uniqueness_of :link
  validates :link, url: true

  acts_as_taggable
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  include Clearance::User

  has_many :resources
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
# frozen_string_literal: true
class PagesController < ApplicationController
  def home
  end
end

app/controllers/resources_controller.rb
# frozen_string_literal: true
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  def index
    if params[:tags].present?
      @resources = Resource.tagged_with([params[:tags]], any: true).order(created_at: :desc).paginate(page: params[:page])
    else
      @resources = Resource.all.includes(:taggings).order(created_at: :desc).paginate(page: params[:page])
    end
    @resources = @resources.where(level: params[:level]) if params[:level].present?
    @resources = @resources.where('cost <= ?', params[:cost]) if params[:cost].present?
  end

  def show
  end

  def new
    @resource = Resource.new
    render :new
  end

  def create
    @resource = new_resource

    if @resource.save
      # fetch_preview
      redirect_to resources_path, notice: successful_create
    else
      render :new
    end
  end

  def destroy
    @resource.destroy
    redirect_to resources_url, notice: 'Resource was successfully destroyed.'
  end

  private

  def set_resource
    @resource = Resource.find(params[:id])
  end

  def new_resource
    if current_user.present?
      current_user.resources.new(resource_params)
    else
      Resource.new(resource_params)
    end
  end

  def resource_params
    params.require(:resource).permit(:title, :description, :image_url, :link, :cost, :level, :tag_list)
  end

  def fetch_preview
    PreviewGenerationJob.perform_later(resource: @resource)
  end

  def successful_create
    return t('.success.user') if current_user.present?
    t('.success.guest')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true
class UsersController < Clearance::UsersController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
  def show_error(object, field)
    messages = object.errors.full_messages_for field
    return if messages.empty?
    content_tag :p, messages.first.lstrip, class: 'field-error'
  end
end

app/helpers/flashes_helper.rb
# frozen_string_literal: true
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice('alert', 'error', 'notice', 'success')
  end
end

app/helpers/full_title_helper.rb
# frozen_string_literal: true
module FullTitleHelper
  def full_title(page_title = '')
    base_title = 'Learning Library'
    if page_title.blank?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/application/_analytics.html.slim
- if ENV['GOOGLE_ANALYTICS_TRACKING_ID']
  javascript:
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', "#{ENV['GOOGLE_ANALYTICS_TRACKING_ID']}", 'auto');
    ga('send', 'pageview');

app/views/application/_css_overrides.html.slim
- if Rails.env.test?
  sass:
    *
      transition-property: none !important

app/views/application/_flashes.html.slim
- if flash.any?
  .flashes
    - user_facing_flashes.each do |type, message|
      = content_tag :div, message, class: "flash-#{type}"

app/views/application/_header.html.slim
header
  nav
    a href=root_path class='logo'

    ul
      li = link_to t('.new_resource'), new_resource_path
      - if signed_in?
        - @user ||= current_user
        li = link_to @user.email, user_path(@user)
        li = link_to t('.sign_out'), sign_out_path, method: :delete
      - else
        li = link_to t('.sign_in'), sign_in_path

app/views/application/_javascript.html.slim
= javascript_include_tag :application

= yield :javascript

= render 'analytics'

- if Rails.env.test?
  coffee:
    $.fx.off = true
    $.ajaxSetup({ async: false })

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta name='ROBOTS' content='NOODP'
    meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'
    title = full_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Roboto:400,700"
    = csrf_meta_tags

    script src="https://use.fontawesome.com/2e861e25d0.js"

  body data-controller=controller_name data-action=action_name
    = render 'header'
    = render 'flashes'

    = yield

    = render 'javascript'
    = render 'css_overrides'

app/views/pages/home.html.slim
h1 Pages#home
p Find me in app/views/pages/home.html.slim

app/views/resources/_form.html.slim
= form_for @resource do |f|
  .field
    = f.label :link, t('.link')
    = f.text_field :link
  = show_error(f.object, :link)

  p = t('.add_tags')

  .field
    = f.label :tag_list, t('.tag_list')
    = f.text_field :tag_list
  .actions
    = f.submit t('.create')

app/views/resources/_resource.html.slim
.resource
  .info
    h2 = resource.title
    a href="#{resource.link}" target='_blank' #{resource.link}
    h3 = resource.description

    ul
      li.money = resource.cost
      li.level = resource.level
      - resource.tag_list.each do |tag|
        li.tag = tag

  img src="#{resource.image_url}" alt="#{resource.title}"

app/views/resources/edit.html.slim
h1 Editing resource

== render 'form'

= link_to 'Show', @resource
'|
= link_to 'Back', resources_path

app/views/resources/index.html.slim
h1 = t('.learn')

.filter
  = form_tag resources_path, method: :get do
    .field
      = label_tag :level
      = select_tag(:level, options_for_select(['beginner', 'intermediate', 'advanced']), { include_blank: true })

    .field
      = label_tag t('.cost')
      = number_field_tag :cost

    .field
      = label_tag :tags
      = text_field_tag :tags

    = submit_tag 'Search', name: nil

= render @resources

= will_paginate @resources

app/views/resources/new.html.slim
= provide :title, t('.title')

h1 = t('.title')

= render 'form'

= link_to 'Back', resources_path

app/views/resources/show.html.slim
p#notice = notice

p
  strong Link:
  = @resource.link

= link_to 'Edit', edit_resource_path(@resource)
'|
= link_to 'Back', resources_path

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.slim
h1 = t('.profile')

= @user.email

ul
  - @user.resources.each do |resource|
    li = resource.link